CREATE TABLE team_member (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL
);

CREATE TABLE booking (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slot_number INTEGER NOT NULL,
    booker_id BIGINT NOT NULL,
    bookie_id BIGINT NOT NULL,

    CONSTRAINT fk_booking_booker FOREIGN KEY (booker_id) REFERENCES team_member(id),
    CONSTRAINT fk_booking_bookie FOREIGN KEY (bookie_id) REFERENCES team_member(id),

    CONSTRAINT uq_booker_slot UNIQUE (booker_id, slot_number),
    CONSTRAINT uq_bookie_slot UNIQUE (bookie_id, slot_number)
);